name: DevOps Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  checkov:
    name: Scan IaC avec Checkov
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Lancer Checkov via Docker
        run: |
          docker run --tty --volume "$(pwd):/scan" bridgecrew/checkov -d /scan

  trivy:
    name: Scan de vulnérabilités avec Trivy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Lancer Trivy via Docker
        run: |
          docker run --tty --volume "$(pwd):/scan" aquasec/trivy fs /scan
